import type { SettingsLanguage } from "./config";

const chinese: Record<string, string> = {
	"Coloring": "配色", "Features": "功能", "Layout": "布局",
	"Built-in segments": "内置页脚项", "Extension segments": "扩展状态项", "Telemetry": "遥测",
	"Language / 语言": "语言 / Language",
	"Choose the language of Zentui settings. Changes apply immediately.": "选择 Zentui 设置界面的语言，切换后立即生效。",
	"Starship/footer colors": "Starship／页脚配色", "Editor + previous messages": "编辑器与历史消息",
	"Choose whether footer runtime/git/context colors use Pi theme tokens or terminal palette styles.": "选择页脚运行环境、Git 和上下文颜色使用 Pi 主题还是终端调色板。",
	"Choose whether editor and previous user-message borders/rails use Pi theme colors or terminal palette styles.": "选择编辑器与历史用户消息的边框、竖线使用 Pi 主题还是终端调色板。",
	"Editor": "编辑器", "Status line": "状态栏", "Message & tool styling": "消息与工具样式", "Copy-friendly mode": "便于复制模式",
	"Enable or disable Zentui's framed editor (model/provider/thinking line).": "开启或关闭 Zentui 边框编辑器，包含模型、服务商和思考级别。",
	"Enable or disable Zentui's custom footer/status line.": "开启或关闭 Zentui 自定义页脚和状态栏。",
	"Style previous user messages, tool blocks, thinking labels and selector borders. Independent of the editor.": "为历史用户消息、工具卡片、思考标签和选择器边框应用样式，独立于编辑器开关。",
	"Hide editor and previous-message rail glyphs for cleaner native terminal selection.": "隐藏编辑器和历史消息的竖线装饰，方便终端原生选区复制。",
	"Footer pulse animation": "页脚渐变动画",
	"Bottom bar & input source": "底栏与输入框来源",
	"pi-open-tui is loaded: choose whether the bottom bar and the input box are drawn by pi-open-tui or by pi-muelsyse-macaron. Changes apply immediately.": "检测到 pi-open-tui：底栏和输入框由 pi-open-tui 还是 pi-muelsyse-macaron 绘制，切换后立即生效。",
	"Shimmer footer gradients while the agent is working (re-renders the screen 4×/s). Off keeps the footer fully static.": "模型工作时播放页脚渐变，每秒重绘 4 次；关闭后页脚保持静止。",
	"Current directory": "当前目录", "Git branch": "Git 分支", "Git status": "Git 状态", "Git counts": "Git 状态数量",
	"Session duration": "会话时长", "Username@host": "用户名@主机", "Current time": "当前时间", "OS icon": "系统图标",
	"Runtime": "运行环境", "Context usage": "上下文用量", "Token counts": "Token 数量", "Cache hit rate": "缓存命中率",
	"Session cost": "会话费用", "Package version": "项目版本", "Git commit": "Git 提交", "Git line metrics": "Git 行数统计",
	"Show or hide the current working directory segment on the left.": "显示或隐藏左侧的当前工作目录。",
	"Show or hide the git branch name on the left.": "显示或隐藏左侧的 Git 分支名。",
	"Show or hide git status icons and ahead/behind markers.": "显示或隐藏 Git 状态图标及领先、落后标记。",
	"Show file status, ahead/behind and stash counts (requires the Git status segment to be enabled).": "显示文件状态、领先／落后提交和 stash 的数量，需要开启 Git 状态项。",
	"Show session running time on the left, after the runtime.": "在左侧运行环境后显示会话运行时长。",
	"Show user@hostname on the left.": "在左侧显示用户名@主机名。",
	"Show the current time (HH:MM) on the right.": "在右侧显示当前时间（HH:MM）。",
	"Show an operating-system icon on the left.": "在左侧显示操作系统图标。",
	"Show or hide the detected runtime/language segment on the left.": "显示或隐藏左侧检测到的运行环境和编程语言。",
	"Show or hide context usage on the right.": "显示或隐藏右侧的上下文用量。",
	"Show or hide input/output token counts on the right.": "显示或隐藏右侧的输入、输出 Token 数量。",
	"Show the latest reply's cache hit rate independently; show 0.0% for zero hits and -- for no data.": "独立显示最近一次回复的缓存命中率；零命中显示 0.0%，无数据显示 --。",
	"Show or hide session cost on the right.": "显示或隐藏右侧的会话费用。",
	"Show the project’s own manifest version (package.json, Cargo.toml, pyproject.toml, …). Distinct from the runtime segment, which shows the installed toolchain version.": "显示项目清单中的版本（package.json、Cargo.toml、pyproject.toml 等），区别于运行环境项中的工具链版本。",
	"Show the current commit hash (and optional exact-match tag). On detached HEAD this provides context the branch segment can’t. Starship `git_commit`-style; default off.": "显示当前提交哈希及可选的精确匹配标签，为游离 HEAD 补充信息。采用 Starship git_commit 样式，默认关闭。",
	"Show aggregate added/deleted line counts (e.g. `+12 −3`) via `git diff HEAD --numstat`. Complements the git status counts. Starship `git_metrics`-style; default off.": "通过 git diff HEAD --numstat 显示新增、删除行数（如 +12 −3），补充 Git 状态数量。采用 Starship git_metrics 样式，默认关闭。",
	"Context style": "上下文样式", "Separator": "分隔符", "Path display": "路径显示", "Path depth": "路径层级", "Branch length": "分支名长度", "Icon mode": "图标模式",
	"Render context as text, a gauge bar, or both.": "上下文用量显示为文字、进度条或两者组合。",
	"Choose the separator between default footer segments.": "选择默认页脚各项之间的分隔符。",
	"Show cwd as basename or full path (home contracted to ~).": "工作目录显示为目录名或完整路径，主目录缩写为 ~。",
	"In full mode, trailing directories to show (0 = all, max 5). Ignored for basename.": "完整路径模式下显示末尾多少层目录：0 表示全部，最多 5 层；目录名模式不使用此项。",
	"Show the full branch name or truncate it to a preset visible width.": "显示完整分支名，或按指定可见宽度截断。",
	"auto/nerd use Nerd Font glyphs; ascii uses plain fallbacks.": "自动和 Nerd Font 模式使用 Nerd Font 字形；纯文本模式使用普通字符。",
	"TPS": "生成速率（TPS）", "TTFT": "首 Token 延迟（TTFT）", "Total duration": "总耗时", "Stall details": "停顿详情", "Cost rate": "费用速率",
	"Show local performance statistics after each task; no network reporting.": "每轮任务结束后显示本地性能统计，不向网络上报。",
	"Output tokens divided by the sum of model request durations, including first-token wait.": "输出 Token 数量除以各次模型请求耗时之和，包含首 Token 等待时间。",
	"Time from the first request to the first text, thinking, or tool-call delta.": "从首轮请求开始到第一个文本、思考或工具调用增量的时间。",
	"Total task duration, including tools and retries.": "整轮任务耗时，包含工具调用及重试。",
	"Total input/output tokens; input splits uncached U (including cache writes) and cached reads R.": "累计输入与输出，输入按未缓存 U（含缓存写入）和缓存读取 R 拆分。",
	"Count and total duration of stream gaps lasting at least one second.": "显示间隔至少 1 秒的流式增量停顿次数和累计时间。",
	"Provider cost divided by total tokens, in dollars per million tokens.": "服务商返回的费用除以总 Token 数，折算为美元／百万 Token。",
	"Managed by /open-tui": "已被 /open-tui 接管",
	"Telemetry is managed by /open-tui; its original tracking, display, and settings are preserved.": "遥测已被 /open-tui 接管，采集、显示和设置沿用插件原有逻辑。",
	"Cache hit rate is managed by /open-tui; its original display conditions and settings are preserved.": "缓存命中率已被 /open-tui 接管，显示条件与设置沿用插件原有逻辑。",
	"No active statuses": "暂无活动状态",
	"This tab only lists statuses currently published through ctx.ui.setStatus().": "此页只列出当前通过 ctx.ui.setStatus() 发布的状态。",
	"Current status": "当前状态", "placement": "位置", "color": "配色",
	"Not publishing a status right now": "当前未发布状态",
	"Live statuses are read through this pack's footer, and /open-tui currently owns the footer, so none can be listed.": "实时状态通过本包页脚读取；当前页脚由 /open-tui 接管，因此无法列出。",
	"theme": "Pi 主题", "terminal": "终端调色板", "mixed": "混合", "enabled": "开启", "disabled": "关闭",
	"off": "隐藏", "left": "左侧", "middle": "中间", "right": "右侧", "zentui": "Zentui 配色", "original": "原始配色",
	"text": "文字", "gauge": "进度条", "text+gauge": "文字与进度条", "pipe": "竖线", "dot": "圆点", "chevron": "箭头", "none": "无",
	"basename": "目录名", "full": "完整", "auto": "自动", "nerd": "Nerd Font", "ascii": "纯文本",
	"Configure Zentui": "配置 Zentui",
	"Footer format cleared (using default layout)": "已清除页脚模板，使用默认布局",
	"Footer format": "页脚模板", "Could not update footer format": "无法更新页脚模板",
	"Could not update Zentui settings": "无法更新 Zentui 设置", "Third-party status": "第三方状态",
	"reload Pi to apply this change": "重新加载 Pi 后应用此修改",
	"another extension is currently managing the editor; reload Pi to apply this change": "编辑器目前由其他扩展管理，重新加载 Pi 后应用此修改",
	"Language saved": "语言已保存",
	"  Enter/Space to change · Tab/Shift+Tab to switch sections · Esc to close": "  Enter／空格 修改 · Tab／Shift+Tab 切换分类 · Esc 关闭",
	"Usage: /zentui [editor|statusline|messages|copy-friendly|pulse] [enable|disable|toggle] or /zentui format \"<template>\"": "用法：/zentui [editor|statusline|messages|copy-friendly|pulse] [enable|disable|toggle]，或 /zentui format \"<template>\"",
	"Zentui fixed-editor was removed. For a pinned editor use Pi's built-in fullscreen mode: set \"tuiMode\": \"fullscreen\" in Pi settings.": "Zentui 固定编辑器已移除。请使用 Pi 内置全屏模式，在 Pi 设置中添加 \"tuiMode\": \"fullscreen\"。",
};

/** 仅翻译设置文案；配置键、命令参数和第三方状态内容保持原样。 */
export function settingsText(text: string, language: SettingsLanguage): string {
	return language === "zh-CN" && Object.hasOwn(chinese, text) ? chinese[text] : text;
}
